# Generated by Django 4.2.9 on 2024-04-03 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tenant", "0004_remove_tenant_id_tenant_tenant_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rota",
            old_name="shift",
            new_name="shift_name",
        ),
        migrations.RenameField(
            model_name="timesheet",
            old_name="shift",
            new_name="shift_name",
        ),
    ]
